// Package dss implements the Distributed Schnorr Signature protocol from the
// paper "Provably Secure Distributed Schnorr Signatures and a (t, n)
// Threshold Scheme for Implicit Certificates".
// https://dl.acm.org/citation.cfm?id=678297
// To generate a distributed signature from a group of participants, the group
// must first generate one longterm distributed secret with the share/dkg
// package, and then one random secret to be used only once.
// Each participant then creates a DSS struct, that can issue partial signatures
// with `dss.PartialSignature()`. These partial signatures can be broadcasted to
// the whole group or to a trusted combiner. Once one has collected enough
// partial signatures, it is possible to compute the distributed signature with
// the `Signature` method.
// The resulting signature is compatible with the EdDSA verification function.
// against the longterm distributed key.
package dss

import (
	"errors"

	"go.dedis.ch/kyber/v4"
	"go.dedis.ch/kyber/v4/share"
)

// Suite represents the functionalities needed by the dss package
type Suite interface {
	kyber.Group
	kyber.HashFactory
	kyber.Random
}

// DistKeyShare is an abstraction to allow one to use distributed key share
// from different schemes easily into this distributed threshold Schnorr
// signature framework.
type DistKeyShare interface {
	PriShare() *share.PriShare
	Commitments() []kyber.Point
}

// DSS holds the information used to issue partial signatures as well as to
// compute the distributed schnorr signature.
type DSS struct {
	suite        Suite
	secret       kyber.Scalar
	public       kyber.Point
	index        uint32
	participants []kyber.Point
	T            uint32
	long         DistKeyShare
	random       DistKeyShare
	longPoly     *share.PubPoly
	randomPoly   *share.PubPoly
	msg          []byte
	partials     []*share.PriShare
	partialsIdx  map[uint32]bool
	signed       bool
	sessionID    []byte
}

// PartialSig is partial representation of the final distributed signature. It
// must be sent to each of the other participants.
type PartialSig struct {
	Partial   *share.PriShare
	SessionID []byte
	Signature []byte
}

var ErrInvalidSignatureIndex = errors.New("dss: partial signature with invalid index")

// NewDSS returns a DSS struct out of the suite, the longterm secret of this
// node, the list of participants, the longterm and random distributed key
// (generated by the dkg package), the message to sign and finally the T
// threshold. It returns an error if the public key of the secret can't be found
// in the list of participants.
func NewDSS(suite Suite, secret kyber.Scalar, participants []kyber.Point,
	long, random DistKeyShare, msg []byte, t uint32) (*DSS, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PartialSig generates the partial signature related to this DSS. This
// PartialSig can be broadcasted to every other participant or only to a
// trusted combiner as described in the paper.
// The signature format is compatible with EdDSA verification implementations.
func (d *DSS) PartialSig() (*PartialSig, error) {
	_ = "STUB: not implemented"
	// following the notations from the paper
	return nil, nil
}

// ProcessPartialSig takes a PartialSig from another participant and stores it
// for generating the distributed signature. It returns an error if the index is
// wrong, or the signature is invalid or if a partial signature has already been
// received by the same peer. To know whether the distributed signature can be
// computed after this call, one can use the `EnoughPartialSigs` method.
func (d *DSS) ProcessPartialSig(ps *PartialSig) error { _ = "STUB: not implemented"; return nil }

// nothing secret here

// EnoughPartialSig returns true if there are enough partial signature to compute
// the distributed signature. It returns false otherwise. If there are enough
// partial signatures, one can issue the signature with `Signature()`.
func (d *DSS) EnoughPartialSig() bool { _ = "STUB: not implemented"; return false }

// Signature computes the distributed signature from the list of partial
// signatures received. It returns an error if there are not enough partial
// signatures. The signature is compatible with the EdDSA verification
// alrogithm.
func (d *DSS) Signature() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// RandomPublic || gamma

func (d *DSS) hashSig() kyber.Scalar {
	_ = "STUB: not implemented"
	// H(R || A || msg) with
	//   - R = distributed random "key"
	//   - A = distributed public key
	//   - msg = msg to sign
	return *new(kyber.Scalar)
}

// Verify takes a public key, a message and a signature and returns an error if
// the signature is invalid.
func Verify(public kyber.Point, msg, sig []byte) error { _ = "STUB: not implemented"; return nil }

// Hash returns the hash representation of this PartialSig to be used in a
// signature.
func (ps *PartialSig) Hash(s Suite) []byte { _ = "STUB: not implemented"; return nil }

func findPub(list []kyber.Point, i uint32) (kyber.Point, bool) {
	_ = "STUB: not implemented"
	return *new(kyber.Point), false
}

func sessionID(s Suite, a, b DistKeyShare) []byte { _ = "STUB: not implemented"; return nil }
